[phases.setup]
nixPkgs = ["nodejs_22", "npm-10_x"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = [
  "npx prisma generate --schema=packages/db/prisma/schema.prisma",
  "cd apps/api && npx tsc"
]

[start]
cmd = "npx prisma migrate deploy --schema=packages/db/prisma/schema.prisma && cd apps/api && node dist/index.js"
